### ISSUE TITLE
(JS-0050) Avoid use of `==` and `!=`

### ISSUE THREAD

**Issue by Xen0Xys** [AmicaleCORE/Jessy#1]
## Description
It is considered good practice to use the type-safe equality operators `===` and `!==` instead of their regular counterparts `==` and `!=`.

## Occurrences
There is 1 occurrence of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/AmicaleCORE/Jessy/issue/JS-0050/occurrences/](https://deepsource.io/gh/AmicaleCORE/Jessy/issue/JS-0050/occurrences/)

**Comment by loicmaes** [comment]
FIXED !!
